server:
  port: 8082

#datasource
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 192.168.150.101:8848 # nacos地址
      discovery:
        namespace: 167e9128-6890-49c3-b9fe-0e45d0124089
        ip: 192.168.150.1
  datasource:
    url: jdbc:mysql://192.168.150.101:3306/sl_trade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: trade-service



#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml